name: qdk
channels:
  - rdkit
  - quantum-engineering
  - conda-forge
dependencies:
  - python=3.7
  - qsharp
  - networkx
  - rdkit
  - pip
  - jupyter
  - pytest
  - ipywidgets
  - pip:
    - ruamel-yaml
    - varname
    - basis_set_exchange
    - jupyter_jsmol
